/* Core UI optional progressive enhancement. Markup uses data-ui-* hooks or ARIA. */
(function () {
    "use strict";
    const instances = new WeakMap();
    const selector = "[data-ui-component],[data-ui-disclosure],[data-ui-tabs],[data-ui-dialog],[data-ui-alert-dialog],[data-ui-sheet],[data-ui-drawer],[data-ui-popover],[data-ui-menu],[data-ui-hovercard],[data-ui-navigation-menu],[data-ui-combobox],[data-ui-select],[data-ui-command],[data-ui-calendar],[data-ui-carousel],[data-ui-otp],[data-ui-resizable],[data-ui-sidebar],[data-ui-toggle],[data-ui-toggle-group],[data-ui-toast-viewport],[data-ui-questionnaire],[data-ui-message-scroller],[data-ui-table]";
    const focusable = "a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex='-1'])";
    const q = (root, value) => root.querySelector(value);
    const qa = (root, value) => Array.from(root.querySelectorAll(value));
    const targetFor = (trigger, root) => document.getElementById(trigger.getAttribute("aria-controls") || trigger.dataset.uiTarget || "") || q(root, trigger.dataset.uiTarget || "[data-ui-content]");
    const setOpen = (trigger, panel, open) => { if (!panel) return; panel.hidden = !open; trigger.setAttribute("aria-expanded", String(open)); };
    const dispatch = (element, name, detail) => element.dispatchEvent(new CustomEvent(name, { bubbles: true, detail }));

    function dialog(root, state) {
        const triggers = qa(document, `[data-ui-target="${root.id}"], [aria-controls="${root.id}"]`);
        const setInert = (active) => qa(document.body, ":scope > *").forEach((child) => { if (child !== root && !child.contains(root)) { if (active) { child.dataset.coreUiInert = child.inert ? "true" : "false"; child.inert = true; } else if (child.dataset.coreUiInert !== undefined) { child.inert = child.dataset.coreUiInert === "true"; delete child.dataset.coreUiInert; } } });
        const close = () => {
            root.hidden = true;
            if (root.tagName === "DIALOG" && root.open) root.close();
            setInert(false);
            document.documentElement.removeAttribute("data-ui-modal-open");
            state.previous && state.previous.focus();
        };
        const open = (event) => { event.preventDefault(); state.previous = event.currentTarget; root.hidden = false; if (root.tagName === "DIALOG" && !root.open) root.showModal(); setInert(true); document.documentElement.setAttribute("data-ui-modal-open", "true"); (q(root, "[autofocus]") || q(root, focusable))?.focus(); };
        triggers.forEach((trigger) => state.on(trigger, "click", open));
        state.on(root, "click", (event) => { if (event.target === root || event.target.closest("[data-ui-close],[data-close]")) close(); });
        state.on(root, "cancel", (event) => { event.preventDefault(); close(); });
        state.on(root, "keydown", (event) => { if (event.key !== "Tab") return; const nodes = qa(root, focusable); if (!nodes.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } });
    }
    function tabs(root, state) {
        const tabs = qa(root, '[role="tab"],[data-ui-tab]');
        const activate = (tab, move) => { tabs.forEach((item) => { const active = item === tab; item.setAttribute("aria-selected", String(active)); item.tabIndex = active ? 0 : -1; const panel = document.getElementById(item.getAttribute("aria-controls")); if (panel) panel.hidden = !active; }); if (move) tab.focus(); };
        tabs.forEach((tab, index) => { state.on(tab, "click", () => activate(tab)); state.on(tab, "keydown", (event) => { const direction = event.key === "ArrowRight" || event.key === "ArrowDown" ? 1 : event.key === "ArrowLeft" || event.key === "ArrowUp" ? -1 : 0; if (event.key === "Home") { event.preventDefault(); activate(tabs[0], true); } else if (event.key === "End") { event.preventDefault(); activate(tabs[tabs.length - 1], true); } else if (direction) { event.preventDefault(); activate(tabs[(index + direction + tabs.length) % tabs.length], true); } }); });
    }
    function popup(root, state) {
        const trigger = q(root, "[data-ui-trigger],[data-ui-part=trigger],[aria-haspopup]"); const panel = q(root, "[data-ui-content],[data-ui-part=content],[data-ui-popover-content],[data-ui-menu-content],[data-ui-hovercard-content],[data-ui-navigation-menu-content]"); if (!trigger || !panel) return;
        const close = () => setOpen(trigger, panel, false); const toggle = (event) => { event.preventDefault(); setOpen(trigger, panel, panel.hidden); };
        state.on(trigger, "click", toggle); state.on(document, "pointerdown", (event) => { if (!root.contains(event.target)) close(); }); state.on(root, "keydown", (event) => { if (event.key === "Escape") { close(); trigger.focus(); } });
        if (root.matches("[data-ui-hovercard]")) { state.on(root, "pointerenter", () => setOpen(trigger, panel, true)); state.on(root, "pointerleave", close); }
    }
    function choices(root, state) {
        const input = q(root, "input"); const items = qa(root, "[data-ui-option],[data-ui-command-item],[role=option]");
        const apply = (item) => { items.forEach((entry) => entry.setAttribute("aria-selected", String(entry === item))); if (input) input.value = item.dataset.value || item.textContent.trim(); dispatch(root, "core-ui:select", { value: input?.value, item }); };
        items.forEach((item) => state.on(item, "click", () => apply(item)));
        if (input) state.on(input, "input", () => { const needle = input.value.toLowerCase(); items.forEach((item) => { item.hidden = !item.textContent.toLowerCase().includes(needle); }); });
    }
    function calendar(root, state) { qa(root, "[data-ui-calendar-day]").forEach((day) => state.on(day, "click", () => { qa(root, "[data-ui-calendar-day]").forEach((item) => item.setAttribute("aria-selected", String(item === day))); dispatch(root, "core-ui:date-change", { value: day.dataset.date || day.value || day.textContent.trim() }); })); }
    function carousel(root, state) { const track = q(root, "[data-ui-carousel-track]"); const slides = qa(root, "[data-ui-carousel-slide]"); let index = 0; const show = (next) => { index = (next + slides.length) % slides.length; if (track) track.style.transform = `translateX(-${index * 100}%)`; dispatch(root, "core-ui:slide-change", { index }); }; qa(root, "[data-ui-carousel-next]").forEach((button) => state.on(button, "click", () => show(index + 1))); qa(root, "[data-ui-carousel-prev]").forEach((button) => state.on(button, "click", () => show(index - 1))); state.on(root, "keydown", (event) => { if (event.key === "ArrowRight") show(index + 1); if (event.key === "ArrowLeft") show(index - 1); }); }
    function otp(root, state) { const fields = qa(root, "input"); fields.forEach((field, index) => { state.on(field, "input", () => { field.value = field.value.slice(-1); if (field.value && fields[index + 1]) fields[index + 1].focus(); }); state.on(field, "keydown", (event) => { if (event.key === "Backspace" && !field.value && fields[index - 1]) fields[index - 1].focus(); }); }); }
    function resizable(root, state) { const handle = q(root, "[data-ui-resize-handle]"); const pane = q(root, "[data-ui-resize-pane]"); if (!handle || !pane) return; const resize = (delta) => { const value = Math.max(0, pane.getBoundingClientRect().width + delta); pane.style.flexBasis = `${value}px`; }; state.on(handle, "pointerdown", (event) => { const start = event.clientX; handle.setPointerCapture(event.pointerId); const move = (next) => resize(next.clientX - start); state.on(handle, "pointermove", move, { once: false }); state.on(handle, "pointerup", () => handle.releasePointerCapture(event.pointerId), { once: true }); }); handle.tabIndex = 0; state.on(handle, "keydown", (event) => { if (event.key === "ArrowLeft") resize(-16); if (event.key === "ArrowRight") resize(16); }); }
    function extras(root, state) {
        qa(root, "[data-ui-toggle]").forEach((button) => state.on(button, "click", () => button.setAttribute("aria-pressed", String(button.getAttribute("aria-pressed") !== "true"))));
        qa(root, "[data-ui-slider-output]").forEach((output) => { const input = document.getElementById(output.htmlFor) || q(root, "input[type=range]"); if (input) { const update = () => { output.textContent = input.value; }; update(); state.on(input, "input", update); } });
        qa(root, "[data-ui-toast] [data-ui-close]").forEach((button) => state.on(button, "click", () => button.closest("[data-ui-toast]").remove()));
        qa(root, "[data-ui-table] th").forEach((header, column) => state.on(header, "click", () => { const table = header.closest("table"); const rows = qa(table, "tbody tr"); const ascending = header.getAttribute("aria-sort") !== "ascending"; qa(table, "th").forEach((item) => item.removeAttribute("aria-sort")); header.setAttribute("aria-sort", ascending ? "ascending" : "descending"); rows.sort((a, b) => a.cells[column].textContent.localeCompare(b.cells[column].textContent, undefined, { numeric: true }) * (ascending ? 1 : -1)).forEach((row) => table.tBodies[0].append(row)); }));
        qa(root, "[data-ui-table-filter]").forEach((input) => state.on(input, "input", () => { const table = document.getElementById(input.getAttribute("aria-controls")) || q(root, "[data-ui-table]"); if (table) qa(table, "tbody tr").forEach((row) => { row.hidden = !row.textContent.toLowerCase().includes(input.value.toLowerCase()); }); }));
        if (root.matches("[data-ui-questionnaire]")) { const questions = qa(root, "[data-ui-question]"); let step = questions.findIndex((item) => !item.hidden); if (step < 0) step = 0; const show = (next) => { step = Math.max(0, Math.min(next, questions.length - 1)); questions.forEach((item, index) => { item.hidden = index !== step; }); dispatch(root, "core-ui:question-change", { step, question: questions[step] }); }; qa(root, "[data-ui-question-next]").forEach((button) => state.on(button, "click", () => { const required = qa(questions[step], "[required]"); if (required.some((field) => !field.checkValidity())) { required.find((field) => !field.checkValidity()).reportValidity(); return; } show(step + 1); })); qa(root, "[data-ui-question-prev]").forEach((button) => state.on(button, "click", () => show(step - 1))); show(step); }
        if (root.matches("[data-ui-message-scroller]")) { const jump = q(root, "[data-ui-jump]"); let follow = root.scrollHeight - root.scrollTop - root.clientHeight < 24; const sync = () => { follow = root.scrollHeight - root.scrollTop - root.clientHeight < 24; if (jump) jump.hidden = follow; }; state.on(root, "scroll", sync); if (jump) state.on(jump, "click", () => { root.scrollTop = root.scrollHeight; sync(); }); const observer = new MutationObserver(() => { if (follow) root.scrollTop = root.scrollHeight; sync(); }); observer.observe(root, { childList: true, subtree: true }); state.observer = observer; sync(); }
    }
    function enhance(root = document) {
        const all = []; if (root.matches?.(selector)) all.push(root); all.push(...qa(root, selector)); all.forEach((element) => { if (instances.has(element)) return; const state = { listeners: [], on(node, type, fn, options) { node.addEventListener(type, fn, options); this.listeners.push([node, type, fn, options]); } }; const component = element.dataset.uiComponent || ""; instances.set(element, state); if (element.matches("[data-ui-disclosure]") || /^(accordion|collapsible)$/.test(component)) { qa(element, "[data-ui-trigger],[data-ui-part=trigger]").forEach((trigger) => state.on(trigger, "click", () => setOpen(trigger, targetFor(trigger, element), trigger.getAttribute("aria-expanded") !== "true"))); } if (element.matches("[data-ui-tabs]") || component === "tabs") tabs(element, state); if (element.matches("[data-ui-dialog],[data-ui-alert-dialog],[data-ui-sheet],[data-ui-drawer]") || /^(alert-dialog|dialog|sheet|drawer)$/.test(component)) dialog(element, state); if (element.matches("[data-ui-popover],[data-ui-menu],[data-ui-hovercard],[data-ui-navigation-menu]") || /^(popover|dropdown-menu|context-menu|menubar|hover-card|navigation-menu|tooltip)$/.test(component)) popup(element, state); if (element.matches("[data-ui-combobox],[data-ui-select],[data-ui-command]") || /^(combobox|select|command)$/.test(component)) choices(element, state); if (element.matches("[data-ui-calendar]") || component === "calendar") calendar(element, state); if (element.matches("[data-ui-carousel]") || component === "carousel") carousel(element, state); if (element.matches("[data-ui-otp]") || component === "input-otp") otp(element, state); if (element.matches("[data-ui-resizable]") || component === "resizable") resizable(element, state); extras(element, state); });
        if (!document.documentElement.dataset.coreUiSidebar) { document.documentElement.dataset.coreUiSidebar = "true"; document.addEventListener("keydown", (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "b") { const sidebar = q(document, "[data-ui-sidebar]"); if (sidebar) { event.preventDefault(); sidebar.hidden = !sidebar.hidden; } } }); }
        return root;
    }
    function destroy(root = document) { const all = []; if (root.matches?.(selector)) all.push(root); all.push(...qa(root, selector)); all.forEach((element) => { const state = instances.get(element); if (!state) return; state.listeners.forEach(([node, type, fn, options]) => node.removeEventListener(type, fn, options)); state.observer?.disconnect(); instances.delete(element); }); return root; }
    window.CoreUI = Object.assign(window.CoreUI || {}, { enhance, destroy });
    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", () => enhance()); else enhance();
}());
