/* Core UI optional progressive enhancement. Generic data-ui-part hooks remain compatible with specialised hooks. */
(function () {
    "use strict";
    const instances = new WeakMap();
    const selector = "[data-ui-component],[data-ui-disclosure],[data-ui-tabs],[data-ui-dialog],[data-ui-alert-dialog],[data-ui-sheet],[data-ui-drawer],[data-ui-popover],[data-ui-menu],[data-ui-hovercard],[data-ui-navigation-menu],[data-ui-combobox],[data-ui-select],[data-ui-command],[data-ui-calendar],[data-ui-carousel],[data-ui-otp],[data-ui-resizable],[data-ui-sidebar],[data-ui-toggle],[data-ui-toggle-group],[data-ui-toast],[data-ui-toast-viewport],[data-ui-questionnaire],[data-ui-message-scroller],[data-ui-table]";
    const focusable = "a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex='-1'])";
    const q = (root, value) => root.querySelector(value);
    const qa = (root, value) => Array.from(root.querySelectorAll(value));
    const part = (root, names) => q(root, names.split(" ").map((name) => `[data-ui-part="${name}"]`).join(","));
    const parts = (root, names) => qa(root, names.split(" ").map((name) => `[data-ui-part="${name}"]`).join(","));
    const panelFor = (trigger, root) => document.getElementById(trigger.getAttribute("aria-controls") || trigger.dataset.uiDialogTarget || trigger.dataset.uiTarget || "") || part(root, "panel dialog menu listbox content") || q(root, "[data-ui-content],[data-ui-popover-content],[data-ui-menu-content],[data-ui-hovercard-content]");
    const emit = (element, name, detail) => element.dispatchEvent(new CustomEvent(name, { bubbles: true, detail }));
    const open = (trigger, panel, value) => { if (!panel) return; panel.hidden = !value; if (trigger) trigger.setAttribute("aria-expanded", String(value)); };
    function add(state, node, type, fn, options) { node.addEventListener(type, fn, options); state.listeners.push([node, type, fn, options]); }
    function modal(root, state) {
        const triggers = qa(root, "[data-ui-part=trigger]");
        const panels = triggers.map((trigger) => panelFor(trigger, root)).filter(Boolean);
        const activate = (panel, trigger) => { state.previous = trigger; panel.hidden = false; trigger.setAttribute("aria-expanded", "true"); qa(document.body, ":scope > *").forEach((node) => { if (node !== panel && !node.contains(panel)) { node.dataset.coreUiInert = String(Boolean(node.inert)); node.inert = true; } }); document.documentElement.dataset.coreUiModalOpen = "true"; (q(panel, "[autofocus]") || q(panel, focusable))?.focus(); };
        const close = (panel) => { panel.hidden = true; triggers.filter((trigger) => panelFor(trigger, root) === panel).forEach((trigger) => trigger.setAttribute("aria-expanded", "false")); qa(document.body, "[data-core-ui-inert]").forEach((node) => { node.inert = node.dataset.coreUiInert === "true"; delete node.dataset.coreUiInert; }); delete document.documentElement.dataset.coreUiModalOpen; state.previous?.focus(); };
        triggers.forEach((trigger) => add(state, trigger, "click", (event) => { event.preventDefault(); const panel = panelFor(trigger, root); if (panel) activate(panel, trigger); }));
        panels.forEach((panel) => { add(state, panel, "click", (event) => { if (event.target === panel || event.target.closest("[data-ui-close],[data-close]")) close(panel); }); add(state, panel, "keydown", (event) => { if (event.key === "Escape") { event.preventDefault(); close(panel); return; } if (event.key !== "Tab") return; const nodes = qa(panel, focusable); if (!nodes.length) return; const first = nodes[0], last = nodes.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }); });
    }
    function disclosure(root, state) { parts(root, "trigger").forEach((trigger) => add(state, trigger, "click", () => { const panel = panelFor(trigger, root); open(trigger, panel, trigger.getAttribute("aria-expanded") !== "true"); })); }
    function tabs(root, state) { const tabs = qa(root, "[role=tab],[data-ui-tab],[data-ui-part=trigger]"); const select = (tab, focus) => { tabs.forEach((item) => { const selected = item === tab; item.setAttribute("aria-selected", String(selected)); item.tabIndex = selected ? 0 : -1; const panel = panelFor(item, root); if (panel) panel.hidden = !selected; }); if (focus) tab.focus(); }; tabs.forEach((tab, index) => { add(state, tab, "click", () => select(tab)); add(state, tab, "keydown", (event) => { const delta = event.key === "ArrowRight" || event.key === "ArrowDown" ? 1 : event.key === "ArrowLeft" || event.key === "ArrowUp" ? -1 : 0; const next = event.key === "Home" ? 0 : event.key === "End" ? tabs.length - 1 : delta ? (index + delta + tabs.length) % tabs.length : null; if (next !== null) { event.preventDefault(); select(tabs[next], true); } }); }); }
    function popup(root, state, type) { const trigger = part(root, "trigger") || q(root, "[aria-haspopup]"); const panel = panelFor(trigger || root, root); if (!trigger || !panel) return; const close = () => open(trigger, panel, false); const show = () => open(trigger, panel, true); add(state, trigger, "click", (event) => { event.preventDefault(); open(trigger, panel, panel.hidden); }); if (type === "context-menu") add(state, trigger, "contextmenu", (event) => { event.preventDefault(); show(); }); add(state, document, "pointerdown", (event) => { if (!root.contains(event.target)) close(); }); add(state, root, "keydown", (event) => { if (event.key === "Escape") { close(); trigger.focus(); } }); if (type === "tooltip" || type === "hover-card") { add(state, trigger, "focus", show); add(state, trigger, "blur", close); add(state, root, "pointerenter", show); add(state, root, "pointerleave", close); } menuKeys(root, state, trigger, panel); }
    function menuKeys(root, state, trigger, panel) { const items = () => qa(panel, "[role^=menuitem]:not([disabled]),[role=option]:not([hidden])"); const move = (next) => { const list = items(); if (!list.length) return; list[(next + list.length) % list.length].focus(); }; add(state, panel, "keydown", (event) => { const list = items(); const at = list.indexOf(document.activeElement); if (event.key === "ArrowDown") { event.preventDefault(); move(at + 1); } else if (event.key === "ArrowUp") { event.preventDefault(); move(at - 1); } else if (event.key === "Home") { event.preventDefault(); move(0); } else if (event.key === "End") { event.preventDefault(); move(list.length - 1); } else if (event.key.length === 1) { const found = list.find((item) => item.textContent.trim().toLowerCase().startsWith(event.key.toLowerCase())); if (found) found.focus(); } }); add(state, trigger, "keydown", (event) => { if (["ArrowDown", "ArrowUp"].includes(event.key)) { event.preventDefault(); open(trigger, panel, true); move(event.key === "ArrowDown" ? 0 : -1); } }); }
    function choices(root, state) { const input = part(root, "input trigger") || q(root, "input[role=combobox]"); const list = part(root, "listbox list") || q(root, "[role=listbox]"); const items = () => qa(list || root, "[role=option],[data-ui-option],[data-ui-command-item]").filter((item) => !item.hidden); let active = 0; const select = (item) => { qa(list || root, "[role=option],[data-ui-option],[data-ui-command-item]").forEach((entry) => entry.setAttribute("aria-selected", String(entry === item))); if (input) { input.value = item.dataset.value || item.textContent.trim(); input.setAttribute("aria-activedescendant", item.id); input.setAttribute("aria-expanded", "false"); } if (list) list.hidden = true; emit(root, "core-ui:select", { value: input?.value, item }); }; items().forEach((item) => add(state, item, "click", () => select(item))); if (!input) return; const show = () => { if (list) list.hidden = false; input.setAttribute("aria-expanded", "true"); }; add(state, input, "focus", show); add(state, input, "input", () => { show(); const needle = input.value.toLowerCase(); items().forEach((item) => { item.hidden = !item.textContent.toLowerCase().includes(needle); }); active = 0; }); add(state, input, "keydown", (event) => { const visible = items(); if (!visible.length) return; if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); show(); active = (active + (event.key === "ArrowDown" ? 1 : -1) + visible.length) % visible.length; input.setAttribute("aria-activedescendant", visible[active].id); visible.forEach((item, index) => item.setAttribute("aria-selected", String(index === active))); } else if (event.key === "Enter") { event.preventDefault(); select(visible[active]); } else if (event.key === "Escape") { if (list) list.hidden = true; input.setAttribute("aria-expanded", "false"); } }); }
    function calendar(root, state) { const days = () => qa(root, "[data-ui-calendar-day], [data-ui-part=grid] button, [data-ui-calendar] button:not([data-ui-part])"); const select = (day, focus) => { days().forEach((item) => { item.setAttribute("aria-selected", String(item === day)); item.tabIndex = item === day ? 0 : -1; }); if (focus) day.focus(); emit(root, "core-ui:date-change", { value: day.dataset.date || day.value || day.getAttribute("aria-label") || day.textContent.trim() }); }; days().forEach((day, index) => { add(state, day, "click", () => select(day)); add(state, day, "keydown", (event) => { const keys = { ArrowRight: 1, ArrowLeft: -1, ArrowDown: 7, ArrowUp: -7, PageDown: 7, PageUp: -7 }; const offset = event.key === "Home" ? -index : event.key === "End" ? days().length - index - 1 : keys[event.key]; if (offset !== undefined) { event.preventDefault(); const all = days(); select(all[Math.max(0, Math.min(index + offset, all.length - 1))], true); } }); }); }
    function carousel(root, state) { const track = q(root, "[data-ui-carousel-track]"); const slides = () => qa(root, "[data-ui-carousel-slide],[data-ui-part=slide]"); let index = Math.max(0, slides().findIndex((slide) => !slide.hidden)); const show = (next) => { const all = slides(); if (!all.length) return; index = (next + all.length) % all.length; all.forEach((slide, item) => { slide.hidden = !track && item !== index; slide.setAttribute("aria-hidden", String(item !== index)); }); if (track) track.style.transform = `translateX(-${index * 100}%)`; emit(root, "core-ui:slide-change", { index }); }; parts(root, "next").forEach((button) => add(state, button, "click", () => show(index + 1))); parts(root, "previous prev").forEach((button) => add(state, button, "click", () => show(index - 1))); add(state, root, "keydown", (event) => { if (event.key === "ArrowRight") show(index + 1); if (event.key === "ArrowLeft") show(index - 1); }); show(index); }
    function otp(root, state) { const fields = qa(root, "[data-ui-part=slot], input"); fields.forEach((field, index) => { add(state, field, "input", () => { field.value = field.value.slice(-1); if (field.value) fields[index + 1]?.focus(); }); add(state, field, "keydown", (event) => { if (event.key === "Backspace" && !field.value) fields[index - 1]?.focus(); }); add(state, field, "paste", (event) => { const text = event.clipboardData?.getData("text").replace(/\s/g, "") || ""; if (!text) return; event.preventDefault(); text.slice(0, fields.length - index).split("").forEach((value, offset) => { fields[index + offset].value = value; }); fields[Math.min(index + text.length, fields.length - 1)].focus(); }); }); }
    function resizable(root, state) { const handle = part(root, "handle") || q(root, "[data-ui-resize-handle]"); const pane = parts(root, "panel")[0] || q(root, "[data-ui-resize-pane]"); if (!handle || !pane) return; const change = (delta) => { const min = Number(handle.getAttribute("aria-valuemin") || 0), max = Number(handle.getAttribute("aria-valuemax") || 100); const container = root.getBoundingClientRect().width || 1; const width = Math.max(container * min / 100, Math.min(container * max / 100, pane.getBoundingClientRect().width + delta)); pane.style.flexBasis = `${width}px`; handle.setAttribute("aria-valuenow", String(Math.round(width / container * 100))); }; add(state, handle, "pointerdown", (event) => { const start = event.clientX; handle.setPointerCapture(event.pointerId); const move = (next) => change(next.clientX - start); add(state, handle, "pointermove", move); add(state, handle, "pointerup", () => handle.releasePointerCapture(event.pointerId), { once: true }); }); add(state, handle, "keydown", (event) => { if (event.key === "ArrowLeft") { event.preventDefault(); change(-16); } if (event.key === "ArrowRight") { event.preventDefault(); change(16); } }); }
    function extras(root, state, component) { const toggles = component === "toggle" || component === "toggle-group" ? parts(root, "trigger") : qa(root, "[data-ui-toggle]"); toggles.forEach((button) => add(state, button, "click", () => { const group = component === "toggle-group" ? root : button.closest("[data-ui-toggle-group]"); const pressed = button.getAttribute("aria-pressed") !== "true"; if (group && group.dataset.multiple !== "true") qa(group, "[aria-pressed]").forEach((item) => item.setAttribute("aria-pressed", "false")); button.setAttribute("aria-pressed", String(pressed)); })); qa(root, "output[for],[data-ui-slider-output]").forEach((output) => { const input = document.getElementById(output.htmlFor) || q(root, "input[type=range]"); if (input) { const update = () => { output.textContent = `${input.value}${output.dataset.unit || (input.max === "100" ? "%" : "")}`; }; update(); add(state, input, "input", update); } }); if (component === "toast" || root.matches("[data-ui-toast]")) { const region = part(root, "region"); const toast = part(root, "toast"); const trigger = part(root, "trigger"); if (toast && region) toast.hidden = true; if (trigger && toast) add(state, trigger, "click", () => { toast.hidden = false; }); qa(root, "[data-ui-close]").forEach((button) => add(state, button, "click", () => (button.closest("[data-ui-part=toast],[data-ui-toast]") || toast)?.remove())); }
        if (component === "sidebar" || root.matches("[data-ui-sidebar]")) { const trigger = part(root, "trigger"), panel = part(root, "panel"); if (trigger && panel) add(state, trigger, "click", () => open(trigger, panel, panel.hidden)); }
        if (component === "data-table" || root.matches("[data-ui-table]")) { const table = q(root, "table") || root; qa(root, "[data-ui-part=sort], th[aria-sort]").forEach((button) => add(state, button, "click", () => { const cell = button.closest("th"); const index = Array.from(cell.parentElement.children).indexOf(cell); const ascending = button.getAttribute("aria-sort") !== "ascending"; qa(table, "th [aria-sort], th[aria-sort]").forEach((item) => item.setAttribute("aria-sort", "none")); button.setAttribute("aria-sort", ascending ? "ascending" : "descending"); qa(table, "tbody tr").sort((a, b) => a.children[index].textContent.localeCompare(b.children[index].textContent, undefined, { numeric: true }) * (ascending ? 1 : -1)).forEach((row) => table.tBodies[0].append(row)); })); qa(root, "[data-ui-filter],[data-ui-table-filter]").forEach((input) => add(state, input, "input", () => qa(table, "tbody tr").forEach((row) => { row.hidden = !row.textContent.toLowerCase().includes(input.value.toLowerCase()); }))); }
        if (component === "questionnaire" || root.matches("[data-ui-questionnaire]")) { const steps = qa(root, "[data-ui-question],[data-ui-part=step]"); let index = Math.max(0, steps.findIndex((step) => !step.hidden)); const update = (next) => { index = Math.max(0, Math.min(next, steps.length - 1)); steps.forEach((step, item) => { step.hidden = item !== index; }); const progress = part(root, "progress"); if (progress) progress.textContent = `Step ${index + 1} of ${steps.length}`; emit(root, "core-ui:question-change", { step: index, question: steps[index] }); }; qa(root, "[data-ui-question-next],[data-ui-part=next]").forEach((button) => add(state, button, "click", (event) => { const invalid = qa(steps[index], "[required]").find((field) => !field.checkValidity()); if (invalid) { event.preventDefault(); invalid.reportValidity(); return; } update(index + 1); })); parts(root, "previous prev").forEach((button) => add(state, button, "click", () => update(index - 1))); update(index); }
        if (component === "message-scroller" || root.matches("[data-ui-message-scroller]")) { const list = part(root, "list") || root, jump = q(root, "[data-ui-jump]") || part(root, "jump"); let follow = false; const sync = () => { follow = list.scrollHeight - list.scrollTop - list.clientHeight < 24; if (jump) jump.hidden = follow; }; add(state, list, "scroll", sync); if (jump) add(state, jump, "click", () => { list.scrollTop = list.scrollHeight; sync(); }); const observer = new MutationObserver(() => { if (follow) list.scrollTop = list.scrollHeight; sync(); }); observer.observe(list, { childList: true, subtree: true }); state.observer = observer; sync(); } }
    function enhance(root = document) { const all = []; if (root.matches?.(selector)) all.push(root); all.push(...qa(root, selector)); all.forEach((element) => { if (instances.has(element)) return; const state = { listeners: [] }; instances.set(element, state); const component = element.dataset.uiComponent || ""; if (/^(accordion|collapsible)$/.test(component) || element.matches("[data-ui-disclosure]")) disclosure(element, state); if (component === "tabs" || element.matches("[data-ui-tabs]")) tabs(element, state); if (/^(dialog|alert-dialog|sheet|drawer)$/.test(component) || element.matches("[data-ui-dialog],[data-ui-alert-dialog],[data-ui-sheet],[data-ui-drawer]")) modal(element, state); if (/^(popover|dropdown-menu|context-menu|menubar|navigation-menu|hover-card|tooltip|date-picker)$/.test(component) || element.matches("[data-ui-popover],[data-ui-menu],[data-ui-hovercard],[data-ui-navigation-menu]")) popup(element, state, component); if (/^(combobox|select|command)$/.test(component) || element.matches("[data-ui-combobox],[data-ui-select],[data-ui-command]")) choices(element, state); if (component === "calendar" || element.matches("[data-ui-calendar]")) calendar(element, state); if (component === "carousel" || element.matches("[data-ui-carousel]")) carousel(element, state); if (component === "input-otp" || element.matches("[data-ui-otp]")) otp(element, state); if (component === "resizable" || element.matches("[data-ui-resizable]")) resizable(element, state); extras(element, state, component); }); if (!document.documentElement.dataset.coreUiSidebar) { document.documentElement.dataset.coreUiSidebar = "true"; document.addEventListener("keydown", (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "b") { const sidebar = q(document, "[data-ui-sidebar]"); const trigger = sidebar && part(sidebar, "trigger"), panel = sidebar && part(sidebar, "panel"); if (trigger && panel) { event.preventDefault(); open(trigger, panel, panel.hidden); } } }); } return root; }
    function destroy(root = document) { const all = []; if (root.matches?.(selector)) all.push(root); all.push(...qa(root, selector)); all.forEach((element) => { const state = instances.get(element); if (!state) return; state.listeners.forEach(([node, type, fn, options]) => node.removeEventListener(type, fn, options)); state.observer?.disconnect(); instances.delete(element); }); return root; }
    window.CoreUI = Object.assign(window.CoreUI || {}, { enhance, destroy });
    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", () => enhance()); else enhance();
}());
