import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderDocumentation } from './docs-render.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registry = JSON.parse(fs.readFileSync(path.join(root, 'registry.json'), 'utf8'));
const mode = process.argv[2] || '--check';
if (!['--write', '--check'].includes(mode)) throw new Error(`Unknown mode: ${mode}`);
const styles = registry.components
  .map(
    (c) =>
      `/* ${c.name} — ${c.files.css} */\n${fs.readFileSync(path.join(root, c.files.css), 'utf8').trim()}`
  )
  .join('\n\n');
const outputs = await renderDocumentation(root, registry);
outputs.set(
  'docs/components.generated.css',
  `/* Generated from registry.json. Run bun run docs:write. */\n\n${styles}\n`
);
// Mirror pseudo-class selectors, keeping component declarations authoritative.
const stateStyles = styles
  .replace(/:focus-visible\b/g, '[data-demo-focus]')
  .replace(/:focus-within\b/g, '[data-demo-focus-within]')
  .replace(/:focus\b/g, '[data-demo-focus]')
  .replace(/:hover\b/g, '[data-demo-hover]')
  .replace(/:active\b/g, '[data-demo-active]')
  .replace(/:indeterminate\b/g, '[data-demo-mixed]');
outputs.set(
  'docs/states.generated.css',
  `/* Generated pseudo-state mirrors for documentation only. */\n@scope ([data-state-surface]) {\n${stateStyles}\n}\n`
);
const bundle = await Bun.build({
  entrypoints: [path.join(root, 'docs/playground.js')],
  target: 'browser',
  format: 'iife',
  minify: true,
  plugins: [
    {
      name: 'docs-behaviors',
      setup(build) {
        build.onResolve({ filter: /^mewa-docs-models$/ }, () => ({
          path: 'models',
          namespace: 'models'
        }));
        build.onLoad({ filter: /.*/, namespace: 'models' }, () => ({
          loader: 'json',
          contents: JSON.stringify(outputs.models)
        }));
        build.onResolve({ filter: /^mewa-docs-behaviors$/ }, () => ({
          path: 'behaviors',
          namespace: 'docs'
        }));
        build.onLoad({ filter: /.*/, namespace: 'docs' }, () => ({
          loader: 'js',
          contents: registry.components
            .filter((c) => c.files.js)
            .map((c) => `import '${path.join(root, c.files.js)}';`)
            .join('\n')
        }));
      }
    }
  ]
});
if (!bundle.success) throw new Error(bundle.logs.join('\n'));
outputs.set(
  'docs/playground.generated.js',
  `/* Generated by bun run docs:write. */\n${(await bundle.outputs[0].text()).trimEnd()}\n`
);
for (const [relative, expected] of outputs) {
  const target = path.join(root, relative);
  if (mode === '--write') {
    fs.writeFileSync(target, expected);
    console.log(`WRITE ${relative}`);
  } else if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== expected) {
    console.error(`FAIL ${relative} is stale; run bun run docs:write`);
    process.exitCode = 1;
  } else console.log(`PASS ${relative}`);
}
