import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderDocumentation, renderComponentStyles } from './docs-render.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registry = JSON.parse(fs.readFileSync(path.join(root, 'registry.json'), 'utf8'));
const mode = process.argv[2] || '--check';
if (!['--write', '--check'].includes(mode)) throw new Error(`Unknown mode: ${mode}`);
const obsoleteStyles = path.join(root, 'docs/states.generated.css');
if (mode === '--write') fs.rmSync(obsoleteStyles, { force: true });
else if (fs.existsSync(obsoleteStyles)) {
  console.error('FAIL docs/states.generated.css is obsolete; run bun run docs:write');
  process.exitCode = 1;
}
const outputs = await renderDocumentation(root, registry);
outputs.set('docs/components.generated.css', renderComponentStyles(root, registry));
const bundle = await Bun.build({
  entrypoints: [path.join(root, 'docs/playground.js')],
  target: 'browser',
  format: 'iife',
  minify: true,
  plugins: [
    {
      name: 'docs-behaviors',
      setup(build) {
        build.onResolve({ filter: /^mewa-docs-models$/ }, () => ({
          path: 'models',
          namespace: 'models'
        }));
        build.onLoad({ filter: /.*/, namespace: 'models' }, () => ({
          loader: 'json',
          contents: JSON.stringify(outputs.models)
        }));
        build.onResolve({ filter: /^mewa-docs-behaviors$/ }, () => ({
          path: 'behaviors',
          namespace: 'docs'
        }));
        build.onLoad({ filter: /.*/, namespace: 'docs' }, () => ({
          loader: 'js',
          contents: registry.components
            .filter((c) => c.files.js)
            .map((c) => `import '${path.join(root, c.files.js)}';`)
            .join('\n')
        }));
      }
    }
  ]
});
if (!bundle.success) throw new Error(bundle.logs.join('\n'));
outputs.set(
  'docs/playground.generated.js',
  `/* Generated by bun run docs:write. */\n${(await bundle.outputs[0].text()).trimEnd()}\n`
);
for (const [relative, expected] of outputs) {
  const target = path.join(root, relative);
  if (mode === '--write') {
    fs.writeFileSync(target, expected);
    console.log(`WRITE ${relative}`);
  } else if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== expected) {
    console.error(`FAIL ${relative} is stale; run bun run docs:write`);
    process.exitCode = 1;
  } else console.log(`PASS ${relative}`);
}
